name: Lint and Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:

  ###########
  # LINTING #
  ###########
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # Cache pip
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: ${{ runner.os }}-pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install mypy black isort
    - name: Python Code Quality and Lint
      uses: abey79/python-lint@master
      with:
        python-root-list: "pnoise tests"
        use-pylint: false
        use-pycodestyle: false
        use-flake8: false
        use-black: true
        extra-black-options: --diff
        use-mypy: true
        use-isort: true

  #########
  # TESTS #
  #########
  tests:
    needs: linting
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install .
        pip install -r dev-requirements.txt
    - name: Pytest
      run: |
        pytest
